# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7c85247f159ae6fc966e9bb34a5223354589fff3ad72522045f82e0d3a01e49fd6c6097d12d5e0f687e5eb8c58c8c480ca91949a40d803a566248f6085ae579

test:
  secret_key_base: ee1651b9feb8aadbc6cc91ff44befc0fa8c8706da962cce132e0c7b194d5c1cf3247f8b02b059dad4d80c7074bf742eb72b06715a72e9620c7fe4ddbe70064ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
